//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pdvshow.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_PDVSHOTYPE                  129
#define IDR_MAINFRAME_TOUC              129
#define IDD_TOUCAN_COLOR                129
#define IDR_MAINFRAME_TF                130
#define IDR_MAINFRAME_FOI               131
#define IDD_DIALOG1                     132
#define IDD_DIALOG2                     142
#define IDR_TOOLBAR1                    149
#define IDD_WATERFALL_CONTROL           169
#define IDC_GAIN_BOX                    1000
#define IDB_PLUGIN_BITMAP               1001
#define IDC_OFFSET_BOX                  1001
#define IDC_EXPOSURE_BOX                1002
#define IDC_GAIN_SLIDER                 1004
#define IDC_OFFSET_SLIDER               1005
#define IDC_EXPOSURE_SLIDER             1006
#define IDAPPLY                         1007
#define IDC_GAIN_VALUE                  1007
#define IDC_OFFSET_VALUE                1008
#define IDC_EXPOSURE_VALUE              1009
#define IDC_BUTTON2                     1010
#define IDC_BUTTON1                     1013
#define IDC_WIDTH_FROM_CAMERA           1018
#define IDC_SLIDER1                     1019
#define IDC_SLIDER2                     1020
#define IDC_ACTIVATE_WATERFALL          1020
#define IDC_LIVE_BUTTON                 1020
#define IDC_GAIN_LABEL                  1021
#define IDC_GAIN_SPIN                   1022
#define IDC_GRAB_BUTTON                 1023
#define IDC_GAIN_LABEL2                 1025
#define IDC_GAIN_LABEL3                 1026
#define IDC_GAIN_LABEL4                 1027
#define IDC_OFFSET_SPIN                 1028
#define IDC_EXPOSE_SPIN                 1029
#define IDC_GAIN_LABEL5                 1030
#define IDC_GAIN_LABEL6                 1031
#define IDC_GAIN_LABEL7                 1032
#define IDC_GAIN_LABEL8                 1033
#define IDC_GAIN_LABEL9                 1034
#define IDC_GAIN_LABEL10                1035
#define IDC_GAIN_LABEL11                1036
#define IDC_GAIN_LABEL12                1037
#define IDC_DECIMAL                     1039
#define IDC_HEX                         1040
#define IDC_HEXIDECIMAL                 1040
#define IDC_ROW1                        1048
#define IDC_ROW2                        1056
#define IDC_WIDTH                       1106
#define IDC_HEIGHT                      1107
#define IDC_ROW0                        1108
#define IDC_USE_RGB_OUT                 1109
#define IDC_WIDTH_SPIN                  1111
#define IDC_ROW0_SPIN                   1112
#define IDC_ROW1_SPIN                   1113
#define IDC_ROW2_SPIN                   1114
#define IDC_HEIGHT_SPIN                 1115
#define IDC_DECIMATE                    1116
#define IDC_DECIMATE_SPIN               1117
#define IDD_CONTRAST                    2130
#define IDD_PIXELTEXT                   2131
#define IDD_HIST_DIALOG                 2132
#define IDD_PROFILE_DIALOG              2133
#define IDD_CAM_CONTROL                 2134
#define IDD_CAM_SETUP                   2135
#define IDD_CAM_PROGRAM                 2136
#define IDD_CAM_CAPTURE                 2137
#define IDD_FILTER_DIALOG               2138
#define IDD_GAMMA_DIALOG                2150
#define IDD_CAM_SELECT                  2151
#define IDD_ZOOM_DIALOG                 2152
#define IDD_LOG_DIALOG                  2153
#define IDD_DATA_PANEL                  2154
#define IDD_ROI_DIALOG                  2155
#define IDD_CAM_CONTROL_DALSA_LS        2156
#define IDD_SOFTWARE_RGB                2157
#define IDD_DVC_CONTROL                 2158
#define IDD_WHITE_BALANCE_SETUP         2161
#define IDD_BINNING_DIALOG              2162
#define IDD_DVC_SETUP_DIALOG            2163
#define IDD_DISPLAY_SKIP_DLG            2164
#define IDD_SICONTROL_DIALOG            2165
#define IDD_DVC_BUTTONS_DLG             2165
#define IDC_SPIN_SHUTTER                3002
#define IDC_EDIT_SHUTTER                3003
#define IDC_EDIT_GAIN                   3005
#define IDC_INFRARED                    3007
#define IDC_HARDWARE_INVERT             3007
#define IDC_SPEED_SCROLL                3008
#define IDC_CURSOR_VALUES               3009
#define IDC_CAMLIST                     3009
#define IDC_SPIN_GAIN                   3009
#define IDC_CAMTYPE                     3010
#define IDC_EDIT_LEVEL                  3010
#define IDC_GAIN_SCROLL                 3011
#define IDC_SPIN_LEVEL                  3012
#define IDC_LEVEL_SCROLL                3013
#define IDC_CAPTURE_MODE                3015
#define IDC_CAPTURE_INDEX               3016
#define IDC_CAPTURE_DIRECTORY           3017
#define IDC_CAPTURE_FILE                3018
#define IDC_BROWSE_DIRECTORIES          3019
#define IDC_CAPTURE_COUNT               3020
#define IDC_CAM_INPUT                   3021
#define IDC_CAPTURE_INTERVAL            3021
#define IDC_MC_INPUT                    3022
#define IDC_CAM_OUTPUT                  3030
#define IDC_LOW_CTRST_SLIDER            3031
#define IDC_HIGH_CTRST_SLIDER           3032
#define IDC_LOW_CTRST_EDIT              3033
#define IDC_HIGH_CTRST_EDIT             3034
#define IDC_APPLY_TO_LIVE               3038
#define IDC_RESET_LIVE                  3039
#define IDC_MODE_LINEAR                 3040
#define IDC_AUTO_LINEAR                 3041
#define IDC_SQRT                        3042
#define IDC_HEQ                         3043
#define IDC_DO_HEQ                      3044
#define IDC_USER_SET                    3045
#define IDC_RGB_RED                     3046
#define IDC_RGB_GREEN                   3047
#define IDC_RGB_BLUE                    3048
#define IDC_GAMMA                       3049
#define IDC_FOLLOW_CURSOR               3102
#define IDC_STARTX                      3125
#define IDC_STARTY                      3126
#define IDC_GOTOXY                      3127
#define IDC_S_NPIXELS                   3128
#define IDC_S_MINPIXEL                  3129
#define IDC_S_MAXPIXEL                  3130
#define IDC_S_MEAN                      3131
#define IDC_S_SD                        3132
#define IDC_S_MEDIAN                    3133
#define IDC_PLOT_WINDOW                 3134
#define IDC_S_MINPIXEL2                 3135
#define IDC_S_MAXPIXEL2                 3136
#define IDC_S_MEAN2                     3137
#define IDC_S_SD2                       3138
#define IDC_S_MEDIAN2                   3139
#define IDC_X_POINT1                    3140
#define IDC_S_MINPIXEL3                 3140
#define IDC_Y_POINT1                    3141
#define IDC_S_MAXPIXEL3                 3141
#define IDC_COMPUTE_BUTTON              3142
#define IDC_S_MEAN3                     3142
#define IDC_X_POINT2                    3143
#define IDC_S_SD3                       3143
#define IDC_Y_POINT2                    3144
#define IDC_S_MEDIAN3                   3144
#define IDC_PROFILE_WINDOW              3145
#define IDC_BITS                        3150
#define IDC_SOURCE1_IMAGE               3151
#define IDC_TARGET_IMAGE                3152
#define IDC_LOW_PASS                    3153
#define IDC_HIGH_PASS                   3154
#define IDC_BUTTON_COMPUTE              3155
#define IDC_SOBEL                       3156
#define IDC_PIXEL_VALUE_WINDOW          3157
#define IDC_PIXEL_VALUE_BUTTON          3158
#define IDC_GAMMA_SLIDER                3300
#define IDC_BIAS_SLIDER                 3301
#define IDC_EDIT1                       3301
#define IDC_LABEL_EDIT2                 3302
#define IDC_ROI_BOTTOM_EDIT             3303
#define IDC_LABEL_EDIT3                 3303
#define IDC_LABEL_EDIT4                 3304
#define IDC_LABEL_EDIT5                 3305
#define IDC_GAMMA_VALUE                 3305
#define IDC_LABEL_EDIT6                 3306
#define IDC_BROWSE_PATH                 3306
#define IDC_CONFIG_PATH                 3307
#define IDC_X_CORNER                    3311
#define IDC_Y_CORNER                    3312
#define IDC_X_SCALE                     3315
#define IDC_Y_SCALE                     3316
#define IDC_SPIN_XCORNER                3317
#define IDC_SPIN_YCORNER                3318
#define ID_CLOSE                        3319
#define IDC_SPIN_ZOOM_SCALE             3320
#define IDC_UPDATE_WINDOW               3321
#define IDC_ADD_TIMESTAMPED             3322
#define IDC_LOG_FILE_NAME               3323
#define IDC_LOGWINDOW                   3324
#define IDC_LOG_COMMENT                 3325
#define IDC_ADD_COMMENT                 3326
#define IDC_CLEAR_LOG_FILE              3327
#define IDC_SAVE_LOG_FILE               3328
#define IDC_GRAYSCALE                   3329
#define IDC_MAXVALUE                    3332
#define IDC_EXPOSE_PERCENT              3332
#define IDC_CAMCONFIG                   3333
#define IDC_DATA_LIST                   3334
#define IDC_FRAME_NUMBER                3335
#define IDC_HSKIP_SLIDER                3336
#define IDC_VSKIP_SLIDER                3337
#define IDC_HACTV_SLIDER                3338
#define IDC_VACTV_SLIDER                3339
#define IDC_HSKIP_EDIT                  3340
#define IDC_HSKIP_MAX                   3341
#define IDC_HSKIP_SPIN                  3342
#define IDC_VSKIP_EDIT                  3343
#define IDC_VSKIP_SPIN                  3344
#define IDC_HACTV_EDIT                  3345
#define IDC_HACTV_SPIN                  3346
#define IDC_VACTV_EDIT                  3347
#define IDC_VACTV_SPIN                  3348
#define IDC_VSKIP_MAX                   3349
#define IDC_HACTV_MAX                   3350
#define IDC_VACTV_MAX                   3351
#define IDC_CLOSE                       3352
#define IDC_APPLY                       3353
#define IDC_LINE_RATE                   3354
#define IDC_LINERATE_SCROLL             3355
#define IDC_EXPOSURE_SCROLL             3356
#define IDC_EDIT_EXPOSURE               3357
#define IDC_EDIT_LINERATE               3358
#define IDC_RED_ROW_FIRST               3361
#define IDC_GREEN_PIXEL_FIRST           3362
#define IDC_SCALE_RED                   3363
#define IDC_SCALE_GREEN                 3364
#define IDC_SCALE_BLUE                  3365
#define IDC_SCALE_RED_SLIDER            3366
#define IDC_SCALE_GREEN_SLIDER          3367
#define IDC_SCALE_BLUE_SLIDER           3368
#define IDC_RGB_GAMMA                   3370
#define IDC_RADIO1                      3371
#define IDC_SPEED2                      3372
#define IDC_RADIO2                      3373
#define IDC_BLACK_OFFSET_SLIDER         3374
#define IDC_SPEED8                      3374
#define IDC_AUTORANGE                   3375
#define IDC_MINVALUE                    3376
#define IDC_SAMPLE_WB                   3377
#define IDC_SAMPLE_PERCENT              3379
#define IDC_USE_RATIOS                  3380
#define IDC_SPEED_VALUE                 3381
#define IDC_TEST_BUTTON                 3382
#define IDC_QUALITY_0                   3383
#define IDC_QUALITY_1                   3384
#define IDC_QUALITY_2                   3385
#define IDC_USE_GAMMA                   3387
#define IDC_BIAS_SPIN                   3388
#define IDC_BIAS_VALUE                  3389
#define IDC_GRADIENT_COLOR              3390
#define IDC_WB_DETAILS                  3391
#define IDC_HBIN2                       3392
#define IDC_HBIN4                       3393
#define IDC_HBIN1                       3394
#define IDC_HBIN8                       3395
#define IDC_HBIN1X2                     3399
#define ID_APPLY                        3400
#define IDC_CAMERA_COMBO                3403
#define IDC_MODE_COMBO                  3404
#define IDC_BINNING_COMBO               3405
#define ID_OK                           3406
#define IDC_OPEN_CAMERA                 3407
#define IDC_APPLY_CAMERA_MODE           3408
#define IDC_APPLY_BINNING               3409
#define IDC_DISPLAY_SKIP_SPIN           3410
#define IDC_DISPLAY_SKIP_VALUE          3411
#define IDC_DISPLAY_SKIP_SLIDER         3412
#define IDC_SAVE_CURRENT1               3415
#define IDC_LOAD_BUTTON1                3416
#define IDC_LOAD_BUTTON2                3417
#define IDC_SAVE_CURRENT2               3418
#define IDC_LOAD_BUTTON3                3419
#define IDC_SAVE_CURRENT3               3420
#define IDC_LOAD_BUTTON4                3421
#define IDC_SAVE_CURRENT4               3422
#define IDC_LOAD_BUTTON5                3423
#define IDC_SAVE_CURRENT5               3424
#define IDC_LOAD_BUTTON6                3425
#define IDC_SAVE_CURRENT6               3426
#define IDC_EXAMINE1                    3427
#define IDC_EXAMINE2                    3428
#define IDC_EXAMINE3                    3429
#define IDC_EXAMINE4                    3430
#define IDC_EXAMINE5                    3431
#define IDC_EXAMINE6                    3432
#define IDC_LABEL_EDIT1                 3433
#define IDC_ENABLE_ROI                  3435
#define IDC_SPEED1                      3436
#define IDC_SPEED4                      3437
#define IDC_ROI_TOP_EDIT                3438
#define IDC_MATRIX_00                   4000
#define IDC_MATRIX_01                   4001
#define IDC_MATRIX_02                   4002
#define IDC_RESET_VALUES                4004
#define IDC_SAMPLE_BLACK                4007
#define IDC_HUE                         4008
#define IDC_SAMPLE_WHITE                4009
#define IDC_MATRIX_10                   4009
#define IDC_MATRIX_11                   4010
#define IDC_SAVE_LEVEL_FILE             4011
#define IDC_MATRIX_12                   4011
#define IDC_MATRIX_20                   4012
#define IDC_DISPLAY_COEFF               4013
#define IDC_MATRIX_21                   4013
#define IDC_LOAD_LEVEL_FILE             4014
#define IDC_MATRIX_22                   4014
#define IDC_KBS_PROPS                   4014
#define IDC_LOAD_CCM2                   4015
#define IDC_CC_00                       4015
#define IDC_LOAD_CCM3                   4016
#define IDC_CC_01                       4016
#define IDC_KBS_SNAP_UNCORRECTED        4016
#define IDC_LOAD_CFG                    4016
#define IDC_CC_02                       4017
#define IDC_CC_10                       4018
#define IDC_KBS_SNAP_CORRECTED          4018
#define IDC_CC_11                       4019
#define IDC_HUE_SLIDER                  4019
#define IDC_KBS_LIVE_CORRECTED          4019
#define IDC_CC_12                       4020
#define IDC_SATURATION_SLIDER           4020
#define IDC_LEVEL_HELP                  4021
#define IDC_CC_20                       4021
#define IDC_CC_21                       4022
#define IDC_CC_22                       4023
#define IDC_LEVEL_HELP2                 4024
#define IDC_SATURATION                  4024
#define IDC_WHITEB_BLUE                 4025
#define IDC_CCM_FILE_NAME               4025
#define IDC_WHITEB_GREEN                4026
#define IDC_SAVE_CCM                    4026
#define IDC_WHITEB_RED                  4027
#define IDC_CONFIG_FILE_NAME            4027
#define IDC_SAVE_CCM2                   4028
#define IDC_BLACK_OFFSET                4028
#define IDC_SAVE_CFG                    4028
#define IDC_LEVEL_FILE_NAME             4029
#define IDC_BLUEGAIN                    4029
#define IDC_GAIN                        4030
#define ID_SAVE_VALUES                  4031
#define IDC_WIZARD_FRAME                4035
#define ID_APPLY_CCM                    4036
#define IDD_PROP_WHITE                  4102
#define IDD_PROP_BLACK                  4137
#define IDD_PROP_CCM                    4138
#define IDD_PROP_ADVANCED               4139
#define IDD_KBS_COLOR                   4140
#define IDD_PROP_COEFF                  4141
#define IDD_PROP_FINISH                 4144
#define IDS_KBSPANEL_PPG_CAPTION        4200
#define IDD_PROPPAGE_KBSPANEL           4200
#define IDC_APPLY_BLACK                 4200
#define IDD_PROP_EXTRAS                 4201
#define IDD_LEVEL_NAME                  4202
#define IDD_CCM_NAME                    4203
#define IDC_WB_LIST                     4204
#define IDC_NEW_LVL                     4205
#define IDC_DEL_LVL                     4206
#define IDC_CCM_LIST                    4207
#define IDC_LEVEL_NAME                  4208
#define IDC_NEW_CCM                     4208
#define IDC_CCM_NAME                    4209
#define IDC_DEL_CCM                     4210
#define ID_APPLY_WB                     4211
#define IDC_RED_SLIDER                  4212
#define IDC_BLUE_SLIDER                 4213
#define IDC_SHARP_0                     4213
#define IDC_GREEN_SLIDER                4214
#define IDC_SHARP1                      4214
#define IDC_SHARP2                      4215
#define IDC_SHARP3                      4216
#define IDC_DETAIL_ONLY                 4217
#define IDC_MED_EDGE_ONLY               4218
#define IDC_CLIP_ON_2                   4219
#define ID_CAMERA_SETTINGS              32771
#define ID_CONTRAST                     32772
#define ID_IMAGE_TEXT                   32773
#define ID_CAMERA_CONTINUOUS            32774
#define ID_DRAW_LINE                    32775
#define ID_CAMERA_INCSPEED              32776
#define ID_CAMERA_DECSPEED              32777
#define ID_CAMERA_CAPTURE               32778
#define ID_HISTOGRAM_SETUP              32779
#define ID_CLEAR_LINE                   32779
#define ID_CAMERA_SETUP                 32782
#define ID_VIEW_PROFILE                 32783
#define ID_FILTER                       32784
#define ID_ARITHMETIC                   32785
#define ID_MASK                         32786
#define ID_Fill                         32787
#define ID_ZOOM_PANEL                   32788
#define ID_VIEW_NORMAL                  32789
#define ID_REMAP_DISPLAY                32790
#define ID_VIEW_ZOOMIN_X2               32792
#define ID_VIEW_ZOOMIN_X4               32793
#define ID_VIEW_ZOOMOUT_X2              32794
#define ID_VIEW_ZOOMOUT_X4              32795
#define ID_CAMERA_PROGRAM               32798
#define ID_CAMERA_COMMAND               32799
#define ID_CAMERA_FILESETTINGS          32802
#define ID_VIEW_CENTERHERE              32803
#define ID_VIEW_CLEARREGION             32805
#define ID_VIEW_SELECTREGION            32807
#define ID_VIEW_REFRESH                 32808
#define ID_VIEW_HISTOGRAM               32809
#define ID_VIEW_TIME_DISPLAY            32811
#define ID_GAMMA                        32812
#define ID_FOIUNIT_1                    32820
#define ID_FOIUNIT_2                    32821
#define ID_FOIUNIT_3                    32822
#define ID_FOIUNIT_0                    32823
#define ID_FOI_CYCLE                    32824
#define ID_RGB_BUTTON                   32827
#define ID_RGB                          32828
#define ID_VIEW_NORMAL_RESET            32834
#define ID_FREERUN                      32836
#define ID_ROI_BUTTON                   32837
#define ID_PLUGIN_TOOLBAR               32838
#define ID_DIRECT_DRAW                  32839
#define ID_KEEP_UP                      32841
#define ID_DRAW_FROM_THREAD             32842
#define ID_BINNING                      32844
#define ID_FOIUNIT_4                    32847
#define ID_DISPLAY_SKIP                 32848
#define ID_FOIUNIT_5                    32851
#define ID_CAMERA_CHECKFOROVERRUN       32852
#define ID_PROCESS_BACKGROUNDSUBTRACT   32853
#define ID_SHOW_SINGLE_FRAME            32855
#define ID_AUTONUMBER                   32856
#define ID_CAMERA_FREERUN               32857
#define ID_INDICATOR_Y                  59143
#define ID_INDICATOR_PIXEL_VALUE        59144
#define ID_INDICATOR_DEBUG              59145
#define ID_INDICATOR_FPS                59146
#define ID_INDICATOR_FRAMES             59147
#define ID_INDICATOR_TIMEOUTS           59148
#define ID_INDICATOR_ZOOM               59149
#define ID_INDICATOR_STATUS             59150
#define ID_INDICATOR_X                  59151

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
