// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef DisplayContrastUI_h
#define DisplayContrastUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <string.h>
#include "PlotWindow.h"
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
extern void contrast_linear_cb(Fl_Round_Button*, void*);
extern void contrast_auto_cb(Fl_Round_Button*, void*);
extern void contrast_heq_cb(Fl_Round_Button*, void*);
extern void contrast_custom_cb(Fl_Round_Button*, void*);
extern void contrast_gamma_cb(Fl_Round_Button*, void*);
#include <FL/Fl_Value_Slider.H>
extern void gamma_slider_cb(Fl_Value_Slider*, void*);
extern void contrast_rawdata_cb(Fl_Round_Button*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
extern void contrast_select_band_cb(Fl_Button*, void*);

class DisplayContrastUI {
public:
  DisplayContrastUI();
  Fl_Double_Window *DisplayContrastWindow;
  PlotWindow *Contrast;
  Fl_Round_Button *LinearMapButton;
  Fl_Round_Button *AutostretchMapButton;
  Fl_Round_Button *HistogramEqualizationButton;
  Fl_Round_Button *CustomMapButton;
  Fl_Round_Button *GammaMapButton;
  Fl_Value_Slider *GammaSlider;
  Fl_Round_Button *RawDataMapButton;
  Fl_Box *MinValueBox;
  Fl_Box *MaxValueBox;
  Fl_Group *ChannelButtons;
  void *owner;
  void show();
};
#endif
