#! /bin/bash

if [ $# -eq 0 ] ; then
	
	csh -c "which fltk-config" > /dev/null 2>&1
	present=$?
	if  [ $present -ne 0 ] ; then

		echo ""
		echo ""
		echo "This program depends on the fltk-1.1.X development package."
		echo "Please install this and rerun this build."
		echo ""
		echo ""

		exit 1
	fi
fi
