// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef LogWindowUI_h
#define LogWindowUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Buffer.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Output.H>

class LogWindowUI {
public:
  LogWindowUI();
  Fl_Double_Window *LogWindow;
private:
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  Fl_Text_Display *LogTextDisplay;
  Fl_Output *LogFileName;
  void add_text(const char *fmt, ...);
};
#endif
