// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef PixelTextUI_h
#define PixelTextUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <string.h>
#include "PixelTable.h"
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Check_Button.H>
extern void follow_cursor_cb(Fl_Check_Button*, void*);
extern void hex_display_cb(Fl_Check_Button*, void*);
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void pixel_text_channel_red_cb(Fl_Button*, void*);
extern void pixel_text_channel_green_cb(Fl_Button*, void*);
extern void pixel_text_channel_blue_cb(Fl_Button*, void*);

class PixelTextUI {
public:
  PixelTextUI(EdtImage *pImage);
  Fl_Double_Window *PixelTextWindow;
  PixelTable *PixelTableWindow;
  Fl_Value_Input *CursorXInput;
  Fl_Value_Input *CursorYInput;
  Fl_Check_Button *FollowCursorCheck;
  Fl_Check_Button *HexDisplayCheck;
  Fl_Group *ChannelButtons;
  void show();
  ~PixelTextUI();
  static void hex_display_cb(Fl_Check_Button *w, void *data);
  void *owner;
};
#endif
