// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef RgbControlUI_h
#define RgbControlUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <string.h>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void rgb_sample_wb_cb(Fl_Button*, void*);
#include <FL/Fl_Value_Slider.H>
extern void rgb_red_slider_cb(Fl_Value_Slider*, void*);
extern void rgb_green_slider_cb(Fl_Value_Slider*, void*);
extern void rgb_blue_slider_cb(Fl_Value_Slider*, void*);
#include <FL/Fl_Box.H>
extern void rgb_gamma_slider_cb(Fl_Value_Slider*, void*);
extern void rgb_apply_cb(Fl_Button*, void*);
extern void rgb_OK_cb(Fl_Button*, void*);
extern void rgb_Cancel_cb(Fl_Button*, void*);
extern void bggr_button_cb(Fl_Button*, void*);
extern void rggb_button_cb(Fl_Button*, void*);
extern void gbrg_button_cb(Fl_Button*, void*);
extern void grbg_button_cb(Fl_Button*, void*);

class RgbControlUI {
public:
  RgbControlUI();
  Fl_Double_Window *RgbControlWindow;
  Fl_Value_Slider *RedSlider;
  Fl_Value_Slider *GreenSlider;
  Fl_Value_Slider *BlueSlider;
  Fl_Value_Slider *GammaSlider;
  Fl_Button *BGGR_Button;
  Fl_Button *RGGB_Button;
  Fl_Button *GBRG_Button;
  Fl_Button *GRBG_Button;
  void *owner; 
  void show();
};
#endif
