
#set basic defines for makefiles under pdv

!IFNDEF ARCH

!IFDEF PROGRAMW6432

ARCH=amd64

!else

ARCH=x86

!ENDIF

!ENDIF

HEADER_DIR =$(PDVHOME)

INCLUDEFLAGS=-I$(HEADER_DIR) -I$(PDVHOME)/tiff/libtiff

INCLUDES = $(HEADER_DIR)/edtinc.h \
        $(HEADER_DIR)/libedt.h \
        $(HEADER_DIR)/libpdv.h \
        $(HEADER_DIR)/libdvu.h \
        $(HEADER_DIR)/edtreg.h \
        $(HEADER_DIR)/edt_bitload.h \
        $(HEADER_DIR)/edt_error.h \
        $(HEADER_DIR)/initcam.h \
        $(HEADER_DIR)/clsim_lib.h \
        $(HEADER_DIR)/pdv_dependent.h

CFG=Release

OPTIM = -O2

!IFDEF BUILD_ID

BUILDFLAGS= -DBUILD=\"$(BUILD_ID)\"

BINDIR=$(PDVHOME)\bin\$(ARCH)

LIBDIR=$(PDVHOME)\lib\$(ARCH)


!ELSE

BUILDFLAGS= 

BINDIR=$(PDVHOME)

LIBDIR=$(PDVHOME)

!ENDIF

#call with ARCH set to x86 or amd64

CFGNAME=$(CFG)$(ARCH)


!IF "$(ARCH)" == "x86"

#MMX_FLAG=-DUSE_MMX
#MMX_LIB=edt_mmx.lib

!ELSE

MMX_FLAG=
MMX_LIB=

!ENDIF


VS2005DEFINES = -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE

CFLAGS = -W3 $(OPTIM) -MD -nologo $(VS2005DEFINES) $(INCLUDEFLAGS) $(MMX_FLAG) $(PSN_FLAG) $(BUILDFLAGS) -DWIN32 

CCFLAGS = -W3 $(OPTIM) -MD -nologo $(VS2005DEFINES) $(INCLUDEFLAGS)  $(MMX_FLAG)  -DWIN32 

LIB32 = link -lib
LIBFLAGS = 

LINK32 = link

LDFLAGS = /LIBPATH:$(LIBDIR)

DLLFLAGS = $(LDFLAGS) /dll /nologo 

LIBS = $(LIBDIR)/pdvlib.lib $(MMX_LIB) $(LIBDIR)/libtiff.lib $(LIBDIR)/edtimage.lib $(LIBDIR)/clseredt.lib

# Windows libraries required by some programs (e.g. win_sysinfo).
WINLIBS = Advapi32.lib user32.lib gdi32.lib
